[project]
name = "psychopy-ledstrip"
description = """This repository contains a [Psychopy](https://psychopy.org/) plugin implementing a
        [component](https://psychopy.org/builder/components/index.html#components) exposing tacking data
        from a [Ledstrip](https://polhemus.com/all-trackers/ledstrip) tracking device. 
        """
readme = "docs/README.md"
requires-python = ">=3.10"
dependencies = [
  "jinja2>=3.1.6",
  "psychopy-fastrak>=0.0.0",
  "psychopy-lib>=2026.1.3",
  "slasd>=1.2.0",
]
dynamic = ["version"]  # Remove any static version = "..." line

[project.entry-points."psychopy.experiment.components"]
# if you want a Component to appear in the "Components" panel, add its class here
LedstripComponent = "psychopy_ledstrip.components.ledstripComponent:LedstripComponent"
LedstripDeviceBackend = "psychopy_ledstrip.components.ledstripComponent:LedstripDeviceBackend"

[project.entry-points."psychopy.hardware"]
# if you want something to be importable from psychopy.hardware, add it here
LedstripHardwareDevice = "psychopy_ledstrip.hardware:LedstripHardwareDevice"
LedstripResponse = "psychopy_ledstrip.hardware:LedstripResponse"

[dependency-groups]
dev = [
  "cairosvg>=2.9.0",
  "ciqar>=0.2.0",
  "fake-bpy-module>=20260501",
  "griffe-typingdoc>=0.3.1",
  "markdown-gfm-admonition @ git+https://github.com/Joecstarr/markdown-gfm-admonition",
  "markdown-include-variants>=0.0.8",
  "mdx-include>=1.4.2",
  "mkdocs-api-autonav>=0.4.0",
  "mkdocs-author-plugin @ git+https://github.com/Joecstarr/mkdocs-author-plugin",
  "mkdocs-auto-refresh-build-pages>=1.0.3",
  "mkdocs-autorefs>=1.4.4",
  "mkdocs-awesome-nav>=3.3.0",
  "mkdocs-bibtex @ git+https://github.com/Joecstarr/mkdocs-bibtex",
  "mkdocs-include-dir-to-nav @ git+https://github.com/Joecstarr/mkdocs_include_dir_to_nav",
  "mkdocs-macros-plugin>=1.5.0",
  "mkdocs-material>=9.7.6",
  "mkdocs-monorepo-plugin>=1.1.2",
  "mkdocs-redirects>=1.2.3",
  "mkdocstrings[python]>=1.0.4",
  "mkdoxy>=1.2.8",
  "parametrize-from-file>=0.20.0",
  "pymdown-extensions>=10.21.2",
  "pyserial-mock>=1.0.0",
  "pytest>=9.0.3",
  "pytest-html>=4.2.0",
  "pytest-mock>=3.15.1",
  "pytest-reportlog>=1.0.0",
  "reloadserver>=1.0.0",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["psychopy_ledstrip"]

[tool.jinja-lsp]
templates = "./templates"
backend = ["./psychopy_ledstrip/components/ledstripComponent/"]

[tool.pytest.ini_options]
pythonpath = [".", "psychopy_ledstrip"]

[tool.ruff]
[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 90

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
  # pydocstyle
  "D"
]
ignore = [
  "UP022",
  "D211",
  "D203",
  "D213",
  "D413",
  "E111",
  "W191",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "E501",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.setuptools.packages.find]
# any folders to ignore when building the Python package for this plugin
exclude = ["docs*", "docs_src*"]

[tool.uv.sources]
mkdocs-bibtex = { git = "https://github.com/Joecstarr/mkdocs-bibtex" }
mkdocs-author-plugin = { git = "https://github.com/Joecstarr/mkdocs-author-plugin" }
markdown-gfm-admonition = { git = "https://github.com/Joecstarr/markdown-gfm-admonition" }
mkdocs-include-dir-to-nav = { git = "https://github.com/Joecstarr/mkdocs_include_dir_to_nav" }

[tool.uv-dynamic-versioning]
style = "semver"  # also "semver" or "pvp"
pattern = "default"  # "default" requires a "v" prefix; "default-unprefixed" drops it

[lint]
line-length = 100